/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/chair.glb -o src/components/Chair.jsx -k -K -r public 
Author: Francesco Coldesina (https://sketchfab.com/topfrank2013)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chair-b5ecdb6253a7454c916954bef6c10251
Title: Chair
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Chair(props) {
  const { nodes, materials } = useGLTF("/chair.glb");
  return (
    <group {...props} dispose={null} scale={0.009}>
      {/* <directionalLight position={[1, 2, 3]} intensity={2} /> */}
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="APezzi1objcleanergles"
            position={[-337.616, -369.778, -444.194]}
          >
            <mesh
              castShadow
              receiveShadow
              name="Object_2"
              geometry={nodes.Object_2.geometry}
              material={materials["default"]}
            ></mesh>
            <mesh
              name="Object_3"
              geometry={nodes.Object_3.geometry}
              material={materials["default"]}
            ></mesh>
            <mesh
              name="Object_4"
              geometry={nodes.Object_4.geometry}
              material={materials["default"]}
            />
            <mesh
              name="Object_5"
              geometry={nodes.Object_5.geometry}
              material={materials["default"]}
            />
            <mesh
              name="Object_6"
              geometry={nodes.Object_6.geometry}
              material={materials["default"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/chair.glb')
