/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/venus.glb -o src/components/Venus.jsx -k -K -r public 
Author: SMK – National Gallery of Denmark (https://sketchfab.com/smkmuseum)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/venus-de-milo-aphrodite-of-milos-53082b5d6cef4c34a9701a2a24f58075
Title: Venus de Milo (Aphrodite of Milos)
*/

import { useRef, useState } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import {
  useGLTF,
  useCursor,
  useTexture,
  Text,
  Decal,
  OrbitControls,
  RenderTexture,
  RandomizedLight,
  PerspectiveCamera,
  AccumulativeShadows,
} from "@react-three/drei";


export default function Venus(props) {
  const textRef = useRef() 
  const {nodes} = useGLTF('/bunny-transformed.glb')
      useFrame((state) => (textRef.current.position.x =
      Math.sin(state.clock.elapsedTime) * 5.5))

  return (
    <>
    <ambientLight intensity={1} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bunny.geometry}
        {...props}
        dispose={null}
        scale={2.5}
      >
        <meshStandardMaterial color="white" />
        <Decal
          position={[0, 0.9, 0.75]}
          rotation={[-0.4, Math.PI, 0]}
          scale={[1.2, 0.45, 1]}
        >
          <meshStandardMaterial
            roughness={1}
            transparent
            polygonOffset
            polygonOffsetFactor={-1}
          >
            <RenderTexture attach="map">
              <PerspectiveCamera
                makeDefault
                manual
                aspect={0.9 / 0.25}
                position={[0, 0, 5]}
              />
              <color attach="background" args={["#af2040"]} />
              <ambientLight intensity={Math.PI} />
              {/* <directionalLight position={[10, 10, 5]} /> */}
              <Text
                rotation={[0, Math.PI, 0]}
                ref={textRef}
                fontSize={4}
                color="white"
              >
                ваш логотип
              </Text>
            </RenderTexture>
          </meshStandardMaterial>
        </Decal>
      </mesh>
      
    </>
  );
}

